name: stack_ds
description: Stack data structure base implementation
version: 1.0.1
homepage: https://github.com/vasov97/stack_package.git

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
